### ISSUE TITLE
DVB Software freezes while attempting to probe card

### ISSUE THREAD

**Issue by mrnamwen** [marcusbirkin/BGT3xxx#14]
Hi again,
The fix from the previous issue works perfectly fine and the driver installs correctly. However, I have noticed a separate issue now that the driver successfully installs.

Whenever a DVB application probes the card, the application hangs and attempting to kill it moves it into a zombie state. I have been able to verify that it is not an issue with the software I was using as this issue occurs on practically every DVB software I use (tvheadend, mythtv, gnutv, w_scan, kaffeine). VLC's DVB mode just presents a blackscreen. lsdvb detects the card but hangs while attempting to gather information about it.

Card used is a BlackGold BGT3600 Dual-Tuner Card. Card is verified working under a windows environment using both DVB-S connections, and the satellite connection has been verified using both the card and an independent Enigma2 unit (VU+ Solo2). Applications do not return any error logs regarding this issue; Kaffeine reports that it is probing the card in its logs before it hangs, however.

**Comment by marcusbirkin** [comment]
Try using the older commit 7fef4ce

**Comment by mrnamwen** [comment]
Uninstalled latest and tested with commit 7fef4ce. Issue still persists on both standard and DKMS install. I am using Arch Linux, and I understand you developed the patch under Ubuntu. Would that cause enough of a discrepency to stop the driver from functioning correctly?

**Comment by marcusbirkin** [comment]
I expect that something major has changed in the latest Kernel.

I no longer have a BGT card due to the lack of manufacturer support and the
horrible build quality of the hardware.
This unfortunately means that now the project will have to die!

If this worked for you on kernel 4.4, then I think this is your only option
now.

**Comment by mrnamwen** [comment]
I understand. On my main system I do indeed use a different card now, one that's more compatible with Linux, after the BGT3600 basically killed off one of its two tuners. I wanted to try and get whatever's left of this card working under my Linux system, but it appears that the card's pretty much dead (both in software and partially in hardware).

I understand that you can't continue with the project, so I'll go ahead and close the issue. Thanks for attempting to correct the issue anyways!
