### ISSUE TITLE
DKMS INSTALL -  not on later later kernels

### ISSUE THREAD

**Issue by richardwh** [marcusbirkin/BGT3xxx#2]
Hi

This work fantastic on 3.16 , but will not work on 3.19 and later.

Guess something has changed in the kernel.

**Comment by marcusbirkin** [comment]
Hello Richard,

Thanks for letting me know, there have been couple of API changes in v3.17 and v3.18.

This should be fixed now.

Marcus

**Comment by richardwh** [comment]
Thank you :-)
