### ISSUE TITLE
No luck with 3.19 

### ISSUE THREAD

**Issue by richardwh** [marcusbirkin/BGT3xxx#3]
Hi Marcus,

No luck with 3.19 (Mint 17.1 x64)....if i revert back to 3.16, all is well again.

sudo dkms build -m BGT3xxx -v 1.0.0.0Fixed

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=3.19.0-21-generic KERNELDIR=/lib/modules/3.19.0-21-generic/build.........(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.19.0-21-generic (x86_64)
Consult /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/make.log for more information.

---

DKMS make.log for BGT3xxx-1.0.0.0Fixed for kernel 3.19.0-21-generic (x86_64)
Mon Jul  6 16:47:31 BST 2015
make -C /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l 
make[1]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
scripts/make_makefile.pl
Updating/Creating .config
./scripts/make_kconfig.pl /lib/modules/3.19.0-21-generic/build /lib/modules/3.19.0-21-generic/build
Preparing to compile for kernel version 3.19.0

**_WARNING:**_ You do not have the full kernel sources installed.
This does not prevent you from building the v4l-dvb tree if you have the
kernel headers, but the full kernel source may be required in order to use
make menuconfig / xconfig / qconfig.

If you are experiencing problems building the v4l-dvb tree, please try
building against a vanilla kernel before reporting a bug.

Vanilla kernels are available at http://kernel.org.
On most distros, this will compile a newly downloaded kernel:

cp /boot/config-`uname -r` <your kernel dir>/.config
cd <your kernel dir>
make all modules_install install

Please see your distro's web site for instructions to build a new kernel.

./scripts/make_myconfig.pl
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make[1]: Entering directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
perl scripts/make_config_compat.pl /lib/modules/3.19.0-21-generic/build ./.myconfig ./config-compat.h
creating symbolic links...
ln -sf . oss
make -C firmware prep
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make -C firmware
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
  CC  ihex2fw
Generating vicam/firmware.fw
Generating dabusb/firmware.fw
Generating dabusb/bitstream.bin
Generating ttusb-budget/dspbootcode.bin
Generating cpia2/stv0672_vp4.bin
Generating av7110/bootcode.bin
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
Kernel build directory is /lib/modules/3.19.0-21-generic/build
make -C /lib/modules/3.19.0-21-generic/build SUBDIRS=/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l CFLAGS="-I/usr/include -D__KERNEL__ -I/include -DEXPORT_SYMTAB" modules
make[2]: Entering directory `/usr/src/linux-headers-3.19.0-21-generic'
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-types.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tda18271-maps.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tda18271-common.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tda18271-fe.o
  LD [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tda18271.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvbdev.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dmxdev.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_demux.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_filter.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_ca_en50221.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.o
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.o
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c: In function 'dvb_net_add_if':
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c:1282:20: error: macro "alloc_netdev" requires 4 arguments, but only 3 given
       dvb_net_setup);
                    ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c:1281:8: error: 'alloc_netdev' undeclared (first use in this function)
  net = alloc_netdev(sizeof(struct dvb_net_priv), "dvb",
        ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c:1281:8: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c: At top level:
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.c:1243:13: warning: 'dvb_net_setup' defined but not used [-Wunused-function]
 static void dvb_net_setup(struct net_device *dev)
             ^
make[3]: *** [/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_net.o] Error 1
make[2]: *** [_module_/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l] Error 2
make[2]: Leaving directory`/usr/src/linux-headers-3.19.0-21-generic'
make[1]: **\* [default] Error 2
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make: **\* [all] Error 2

**Comment by marcusbirkin** [comment]
Hello Richard,

That seems to stall on one of the issues I had fixed.
Ensure the build environment is up to date (git pull) and clean (make clean).
If all else fails delete your download/source directory and re download.

Regards,

Marcus
