### ISSUE TITLE
build against 4.2 kernel

### ISSUE THREAD

**Issue by richardwh** [marcusbirkin/BGT3xxx#4]
hi, just making you aware of some code that needs fixing...... when i build against a later kernel i get some abuse back....

DKMS make.log for BGT3xxx-1.0.0.0Fixed for kernel 4.2.0-18-generic (x86_64)
Sun Nov 15 17:48:23 GMT 2015
make -C /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l 
make[1]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
scripts/make_makefile.pl
Updating/Creating .config
./scripts/make_kconfig.pl /lib/modules/4.2.0-18-generic/build /lib/modules/4.2.0-18-generic/build
Preparing to compile for kernel version 3.19.0

**_WARNING:**_ You do not have the full kernel sources installed.
This does not prevent you from building the v4l-dvb tree if you have the
kernel headers, but the full kernel source may be required in order to use
make menuconfig / xconfig / qconfig.

If you are experiencing problems building the v4l-dvb tree, please try
building against a vanilla kernel before reporting a bug.

Vanilla kernels are available at http://kernel.org.
On most distros, this will compile a newly downloaded kernel:

cp /boot/config-`uname -r` <your kernel dir>/.config
cd <your kernel dir>
make all modules_install install

Please see your distro's web site for instructions to build a new kernel.

./scripts/make_myconfig.pl
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make[1]: Entering directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
perl scripts/make_config_compat.pl /lib/modules/4.2.0-18-generic/build ./.myconfig ./config-compat.h
creating symbolic links...
ln -sf . oss
make -C firmware prep
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make -C firmware
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
  CC  ihex2fw
Generating vicam/firmware.fw
Generating dabusb/firmware.fw
Generating dabusb/bitstream.bin
Generating ttusb-budget/dspbootcode.bin
Generating cpia2/stv0672_vp4.bin
Generating av7110/bootcode.bin
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
Kernel build directory is /lib/modules/4.2.0-18-generic/build
make -C /lib/modules/4.2.0-18-generic/build SUBDIRS=/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l CFLAGS="-I/usr/include -D__KERNEL__ -I/include -DEXPORT_SYMTAB" modules
make[2]: Entering directory `/usr/src/linux-headers-4.2.0-18-generic'
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.o
In file included from /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.h:21:0,
                 from /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.c:14:
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:282:7: error: unknown type name 'fe_status_t'
       fe_status_t *status);
       ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:292:46: error: unknown type name 'fe_status_t'
  int (*read_status)(struct dvb_frontend* fe, fe_status_t* status);
                                              ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:301:52: error: unknown type name 'fe_sec_mini_cmd_t'
  int (*diseqc_send_burst)(struct dvb_frontend* fe, fe_sec_mini_cmd_t minicmd);
                                                    ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:302:43: error: unknown type name 'fe_sec_tone_mode_t'
  int (*set_tone)(struct dvb_frontend* fe, fe_sec_tone_mode_t tone);
                                           ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:303:46: error: unknown type name 'fe_sec_voltage_t'
  int (*set_voltage)(struct dvb_frontend* fe, fe_sec_voltage_t voltage);
                                              ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:341:2: error: unknown type name 'fe_modulation_t'
  fe_modulation_t  modulation;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:343:2: error: unknown type name 'fe_sec_voltage_t'
  fe_sec_voltage_t voltage;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:344:2: error: unknown type name 'fe_sec_tone_mode_t'
  fe_sec_tone_mode_t sectone;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:345:2: error: unknown type name 'fe_spectral_inversion_t'
  fe_spectral_inversion_t inversion;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:346:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  fec_inner;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:347:2: error: unknown type name 'fe_transmit_mode_t'
  fe_transmit_mode_t transmission_mode;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:349:2: error: unknown type name 'fe_guard_interval_t'
  fe_guard_interval_t guard_interval;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:350:2: error: unknown type name 'fe_hierarchy_t'
  fe_hierarchy_t  hierarchy;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:352:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  code_rate_HP;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:353:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  code_rate_LP;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:355:2: error: unknown type name 'fe_pilot_t'
  fe_pilot_t  pilot;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:356:2: error: unknown type name 'fe_rolloff_t'
  fe_rolloff_t  rolloff;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:358:2: error: unknown type name 'fe_delivery_system_t'
  fe_delivery_system_t delivery_system;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:371:6: error: unknown type name 'fe_code_rate_t'
      fe_code_rate_t fec;
      ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:372:6: error: unknown type name 'fe_modulation_t'
      fe_modulation_t modulation;
      ^
make[3]: *** [/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.o] Error 1
make[2]: *** [_module_/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l] Error 2
make[2]: Leaving directory`/usr/src/linux-headers-4.2.0-18-generic'
make[1]: **\* [default] Error 2
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make: **\* [all] Error 2

**Comment by marcusbirkin** [comment]
Hello Richard,

I've made some changes and pushed this to a new branch. 
https://github.com/marcusbirkin/BGT3xxx/tree/4.2

Marcus

**Comment by richardwh** [comment]
Hi, i tried again and got some different abuse with the new branch....

DKMS make.log for BGT3xxx-1.0.0.0Fixed for kernel 4.2.0-18-generic (x86_64)
Sat Nov 21 11:49:47 GMT 2015
make -C /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l 
make[1]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
scripts/make_makefile.pl
Updating/Creating .config
./scripts/make_kconfig.pl /lib/modules/4.2.0-18-generic/build /lib/modules/4.2.0-18-generic/build
Preparing to compile for kernel version 4.2.0

**_WARNING:**_ You do not have the full kernel sources installed.
This does not prevent you from building the v4l-dvb tree if you have the
kernel headers, but the full kernel source may be required in order to use
make menuconfig / xconfig / qconfig.

If you are experiencing problems building the v4l-dvb tree, please try
building against a vanilla kernel before reporting a bug.

Vanilla kernels are available at http://kernel.org.
On most distros, this will compile a newly downloaded kernel:

cp /boot/config-`uname -r` <your kernel dir>/.config
cd <your kernel dir>
make all modules_install install

Please see your distro's web site for instructions to build a new kernel.

./scripts/make_myconfig.pl
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make[1]: Entering directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
perl scripts/make_config_compat.pl /lib/modules/4.2.0-18-generic/build ./.myconfig ./config-compat.h
creating symbolic links...
ln -sf . oss
make -C firmware prep
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
make -C firmware
make[2]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
  CC  ihex2fw
Generating vicam/firmware.fw
Generating dabusb/firmware.fw
Generating dabusb/bitstream.bin
Generating ttusb-budget/dspbootcode.bin
Generating cpia2/stv0672_vp4.bin
Generating av7110/bootcode.bin
make[2]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/firmware'
Kernel build directory is /lib/modules/4.2.0-18-generic/build
make -C /lib/modules/4.2.0-18-generic/build SUBDIRS=/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l CFLAGS="-I/usr/include -D__KERNEL__ -I/include -DEXPORT_SYMTAB" modules
make[2]: Entering directory `/usr/src/linux-headers-4.2.0-18-generic'
  CC [M]  /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.o
In file included from /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.h:21:0,
                 from /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.c:14:
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:280:7: error: unknown type name 'fe_status_t'
       fe_status_t *status);
       ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:290:46: error: unknown type name 'fe_status_t'
  int (*read_status)(struct dvb_frontend* fe, fe_status_t* status);
                                              ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:299:52: error: unknown type name 'fe_sec_mini_cmd_t'
  int (*diseqc_send_burst)(struct dvb_frontend* fe, fe_sec_mini_cmd_t minicmd);
                                                    ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:300:43: error: unknown type name 'fe_sec_tone_mode_t'
  int (*set_tone)(struct dvb_frontend* fe, fe_sec_tone_mode_t tone);
                                           ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:301:46: error: unknown type name 'fe_sec_voltage_t'
  int (*set_voltage)(struct dvb_frontend* fe, fe_sec_voltage_t voltage);
                                              ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:339:2: error: unknown type name 'fe_modulation_t'
  fe_modulation_t  modulation;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:341:2: error: unknown type name 'fe_sec_voltage_t'
  fe_sec_voltage_t voltage;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:342:2: error: unknown type name 'fe_sec_tone_mode_t'
  fe_sec_tone_mode_t sectone;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:343:2: error: unknown type name 'fe_spectral_inversion_t'
  fe_spectral_inversion_t inversion;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:344:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  fec_inner;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:345:2: error: unknown type name 'fe_transmit_mode_t'
  fe_transmit_mode_t transmission_mode;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:347:2: error: unknown type name 'fe_guard_interval_t'
  fe_guard_interval_t guard_interval;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:348:2: error: unknown type name 'fe_hierarchy_t'
  fe_hierarchy_t  hierarchy;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:350:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  code_rate_HP;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:351:2: error: unknown type name 'fe_code_rate_t'
  fe_code_rate_t  code_rate_LP;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:353:2: error: unknown type name 'fe_pilot_t'
  fe_pilot_t  pilot;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:354:2: error: unknown type name 'fe_rolloff_t'
  fe_rolloff_t  rolloff;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:356:2: error: unknown type name 'fe_delivery_system_t'
  fe_delivery_system_t delivery_system;
  ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:369:6: error: unknown type name 'fe_code_rate_t'
      fe_code_rate_t fec;
      ^
/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/dvb_frontend.h:370:6: error: unknown type name 'fe_modulation_t'
      fe_modulation_t modulation;
      ^
make[3]: *** [/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l/tuner-simple.o] Error 1
make[2]: *** [_module_/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l] Error 2
make[2]: Leaving directory`/usr/src/linux-headers-4.2.0-18-generic'
make[1]: **\* [default] Error 2
make[1]: Leaving directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l'
make: **\* [all] Error 2

**Comment by marcusbirkin** [comment]
Hello Richard,

That's the same set of errors.

What commands are you typing to switch branches and pull the code?

What is the output from: git log -1

Regards,

Marcud

**Comment by richardwh** [comment]
Hi Marcus,

I'm copying and pasting the commands from the dkms install, the same as 
before, not realizing they are identical in both branches so its going 
to default to the master branch.

My git and DKMS knowledge is limited (learning fast), How do you switch 
branches?

Regards
Richard

  DKMS INSTALL

**Comment by marcusbirkin** [comment]
Hello Richard,

Switch to the source directory: cd /usr/src/BGT3xxx
Change to git branch 4.2 (as root): sudo git checkout 4.2
Get latest copy from GitHub (as root): sudo git pull
(optional) Ensure we don't have any unmatched files (as root): sudo git reset --hard
(optional) Display what commit level we are at: git log -1
Build via dkms: sudo dkms build -m BGT3xxx -v 1.0.0.0Fixed

When this branch is confirmed as working I'll merge it back into master, so you'll need to switch back later.
This website (http://gitref.org/) has good info about how git works :)

Regards,

Marcus
