### ISSUE TITLE
Unable to repeat installation

### ISSUE THREAD

**Issue by goneawa** [marcusbirkin/BGT3xxx#7]
I have 2 systems running Ubuntu 3.19.0-56. The older system has a successful DKMS install of BGT3xxx from January. I am now trying to repeat the driver installation on the second machine but have failed. All ok until "sudo dkms build -m BGT3xxx -v 1.0.0.0Fixed" when the terminal returns;
"make KERNELRELEASE=3.19.0.59-generic KERNELDIR=/lib/modules/3.19.0.56-generic/build......(bad exit ststus:2)
ERROR (dkms apport):binary package for BGT3xxx: 1.0.0.0Fixed not found
Error! Bad return status for module build on kernel: 3.19.0.56-generic (x86_64)"

The BGT3xxx/1.0.0.0Fixed/build/make.log shows:

DKMS make.log for BGT3xxx-1.0.0.0Fixed for kernel 3.19.0-56-generic (x86_64) 
Sat Mar 26 17:39:13 GMT 2016 
make -C /var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l 
make[1]: Entering directory `/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l' 
scripts/make_makefile.pl 
make[1]: execvp: scripts/make_makefile.pl: Permission denied 
Updating/Creating .config 
./scripts/make_kconfig.pl /lib/modules/3.19.0-56-generic/build /lib/modules/3.19.0-56-generic/build 
make[1]: execvp: ./scripts/make_kconfig.pl: Permission denied 
make[1]: *** No rule to make target`.myconfig', needed by `config-compat.h'. Stop. 
make[1]: Leaving directory`/var/lib/dkms/BGT3xxx/1.0.0.0Fixed/build/v4l' 
make: **\* [all] Error 2

Two questions, 
What am I doing wrong?
Is it possible to install the driver by copying modules and files from the working installation?

Any guidance gratefully received.

Peter.

**Comment by marcusbirkin** [comment]
It looks like your not running as root.
Try just running the build.sh script as root.
