### ISSUE TITLE
build issues with kernel 4.2.0-34

### ISSUE THREAD

**Issue by adrianeaton** [marcusbirkin/BGT3xxx#8]
Hi,

I've tried your build against ubuntu server trusty 14.04 with kernel 4.2.0-34 but ran into some errors. Any ideas?
Thanks,
Adrian
[dkmsbuild.txt](https://github.com/marcusbirkin/BGT3xxx/files/200479/dkmsbuild.txt)

**Comment by marcusbirkin** [comment]
It looks like the dvb api has changed type defs again.

I'll update it soon

**Comment by marcusbirkin** [comment]
So it turns out that I had already made these changes back in November (https://github.com/marcusbirkin/BGT3xxx/commit/97f4603b18017f8f1b530a7c93fe16823f6b8ff3) and merged into the main branch in December.
Please update your local git copy: https://git-scm.com/docs/git-pull

FYI my main DVB server runs Ubuntu 14.04.4 LTS (Linux 3.13.0-77), my development setup runs Ubuntu 15.10 (Linux 4.20.0-34).

**Comment by adrianeaton** [comment]
I only setup this server 2 weeks ago so not sure how I don't have the latest code. I have tried other repos with the drivers maybe there is some source code overlap. I will try removing everything and starting from scratch. I appreciate your fast response. 
Adrian

**Comment by adrianeaton** [comment]
I have removed all BGT36xxx directories in /usr/src and pulled the latest code. I am sure I have the latest source code from master and git pull shows it is up to date. I use git everyday at work but i don't know linux build process. I have run sudo dkms remove -m BGT3xxx/1.0.0.0Fixed --all to remove all packages is this all I need to do to clean the system? 
Thanks for your effort in maintaining the drivers.

**Comment by marcusbirkin** [comment]
What is the output from the following commands:
uname -a
lsb_release -a
cd /usr/src/BGT3xxx && git log -1

**Comment by adrianeaton** [comment]
Linux george 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

adrian@george:/usr/src$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

adrian@george:/usr/src$ cd /usr/src/BGT3xxx && git log -1
commit 08a6fd7f01ae92025c6435482825c529e492dd33
Merge: 58dd137 e35aeac
Author: marcusbirkin marcusbirkin@users.noreply.github.com
Date:   Sat Dec 5 17:29:12 2015 +0000

```
Merge pull request #5 from marcusbirkin/4.2

4.2
```

**Comment by marcusbirkin** [comment]
run the build.sh script, what is the output from that?

**Comment by adrianeaton** [comment]
[buildoutput.txt](https://github.com/marcusbirkin/BGT3xxx/files/200774/buildoutput.txt)
attached

**Comment by marcusbirkin** [comment]
create a new file called version_test.c the following content and then run gcc version_test.c What is the output from that?

`#include <linux/version.h>`
`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,2,0)`
`#warning "OK"`
`#else`
`#error "NOT OK"`
`#endif`

**Comment by adrianeaton** [comment]
adrian@george:/usr/src/vertest$ sudo gcc version_test.c
version_test.c:5:2: error: #error "NOT OK"
 #error "NOT OK"
  ^

**Comment by marcusbirkin** [comment]
Sorry the code formatting got messed up in the post, ensure you have this:

`#include <linux/version.h>`
`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,2,0)`
`#warning "OK"`
`#else`
`#error "NOT OK"`
`#endif`

**Comment by adrianeaton** [comment]
adrian@george:/usr/src/vertest$ sudo gcc version_test.c
version_test.c:5:2: error: #error "NOT OK"
 #error "NOT OK"
  ^
adrian@george:/usr/src/vertest$ cat version_test.c
#include <linux/version.h>
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,2,0)
#warning "OK"
#else
#error "NOT OK"
#endif

**Comment by marcusbirkin** [comment]
I'm not sure how you've installed kernel 4.2 in Ubuntu 14.04 (Trusty Tahr) as the latest kernel for that is 3.13.0) - See the rmadison output below...
I think maybe you have some kind of kernel source/header mix up, as the version.h header file is claiming not be from kernel v4.2.
I would suggest that you only install the maintained packages from apt.
If you desperately must run kernel v4.2, then upgrade to Ubuntu 15.10 (Wily Werewolf).

$ rmadison linux-generic
 linux-generic | 3.2.0.23.25   | precise          | amd64, i386
 linux-generic | 3.2.0.101.117 | precise-security | amd64, i386
 linux-generic | 3.2.0.101.117 | precise-updates  | amd64, i386
 linux-generic | 3.13.0.24.28  | trusty           | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.13.0.83.89  | trusty-security  | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.13.0.83.89  | trusty-updates   | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.13.0.85.91  | trusty-proposed  | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.19.0.15.14  | vivid            | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.19.0.56.54  | vivid-security   | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.19.0.56.54  | vivid-updates    | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 3.19.0.58.56  | vivid-proposed   | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 4.2.0.16.18   | wily             | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 4.2.0.34.37   | wily-security    | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 4.2.0.34.37   | wily-updates     | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 4.2.0.35.38   | wily-proposed    | amd64, arm64, armhf, i386, ppc64el
 linux-generic | 4.4.0.16.17   | xenial           | amd64, arm64, armhf, i386, ppc64el, s390x
 linux-generic | 4.4.0.17.18   | xenial-proposed  | amd64, arm64, armhf, i386, ppc64el, s390x

**Comment by adrianeaton** [comment]
I just want a linux server that works with blackgold card really. I have only got plex server running on this so far other than that should be standard ubuntu server. I have obviously copied a statement that I shouldnt.  Anyway to reset it or do I need to reinstall os?

**Comment by marcusbirkin** [comment]
With out knowing how you've forced v4.2, i don't know.
You could try: sudo apt-get -f install linux-generic

**Comment by adrianeaton** [comment]
ok thanks for your help. the install worked but doesn't seem to have downgraded the kernel. according to uname -a. Maybe time for a rebuild

**Comment by adrianeaton** [comment]
reinstalled ubuntu only to find 4.2 comes as standard, http://releases.ubuntu.com/14.04.4/ubuntu-14.04.4-server-amd64.iso. oh well it was good to move the system and data onto seperate disks i suppose.

**Comment by marcusbirkin** [comment]
What is the contents of /usr/include/linux/version.h

**Comment by adrianeaton** [comment]
version.h
#define LINUX_VERSION_CODE 199947
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

I have now got the drivers working with this system using code from this repo http://www.cblinux.co.uk:5010/BGT3xxx maintained by Carl (Trident01). I think he has posted in other threads here about combining yours and his work. He has links with Blackgold.

Here is my post about the steps I used to get it to work. 
https://www.avforums.com/threads/building-black-gold-bgt3xxx-dvb-t2-drivers-for-linux.1886692/page-4#post-23438015

Thanks for your help. 
Adrian

**Comment by marcusbirkin** [comment]
That will be why is doesn't work. 
#define LINUX_VERSION_CODE 199947 = v3.13

You still have mismached header files. You will find this will cause problems with other code in the future.

**Comment by marcusbirkin** [comment]
sudo apt-get install linux-headers-$(uname -r)

**Comment by adrianeaton** [comment]
I am not sure what is going on and I haven't run the above install statement yet. I found a query below that seems to show them installed? 
adrian@george:~$ uname -r
4.2.0-34-generic
adrian@george:~$ dpkg-query -s linux-headers-$(uname -r)
Package: linux-headers-4.2.0-34-generic
Status: install ok installed

I have these directories already :
adrian@george:/usr/src$ ll
drwxr-xr-x 24 root root 4096 Apr  3 08:59 linux-headers-3.13.0-83/
drwxr-xr-x  7 root root 4096 Apr  3 08:59 linux-headers-3.13.0-83-generic/
drwxr-xr-x 24 root root 4096 Apr  2 21:35 linux-headers-4.2.0-34/
drwxr-xr-x  7 root root 4096 Apr  2 21:35 linux-headers-4.2.0-34-generic/

I have only installed dkms, software-properties-common and git packages so far.

**Comment by marcusbirkin** [comment]
So I've spun up Ubuntu 14.04-4 server (from that ISO link infact) in a VM.

The package that controls the version headers is "linux-kernel-headers" which includes the package "linux-libc-dev". That package in Ubuntu 14.04-4 is still at v3.13

So I think they've included kernel 4.2 in this release of Ubuntu but not updated everything required.
I expect because they are concentrating on the next LTS due out this month.

Until Ubuntu fix this, you could force it with modifying version.h to read:
`#define LINUX_VERSION_CODE 262656`
`#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))`
